# Generated by Django 5.2.6 on 2025-09-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_de_aniversario', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_da_peca', models.CharField(choices=[('anel', 'Anel'), ('brinco', 'Brinco'), ('colar', 'Colar'), ('pulseira', 'Pulseira'), ('outros', 'Outros')], max_length=50)),
                ('descricao_da_peca', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('foto_da_peca', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('data_de_registro_da_peca', models.DateTimeField(auto_now_add=True)),
                ('valor_de_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_de_venda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
                ('valor_de_compra_praticado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_de_venda_praticado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_da_peca', models.CharField(max_length=50)),
                ('descricao_da_peca', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.produto')),
            ],
        ),
    ]
